# -*- coding: utf-8 -*-
"""Copy of template.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2AfEKRZKsZXk0YJjBWcyLMvzvCFee6G
"""

import geopandas as gpd

# from zip
linkGitZip="https://github.com/tareas1234512/tareas/raw/main/cb_2018_us_state_20m.zip"
gdf1 = gpd.read_file(linkGitZip)
gdf1.head()

gdf1.plot()

# from shapefile in a folder
linkGitSHP="https://github.com/tareas1234512/tareas/raw/main/cb_2018_us_state_20m/cb_2018_us_state_20m.shp"
gdf2 = gpd.read_file(linkGitSHP)
gdf2.head()

"""# Do something"""

# Export to  GeoPackage
gdf1.to_file('MapFromPython1.gpkg', driver='GPKG', layer='usa')

# With additional options
gdf2.to_file('MapFromPython2.geojson',
           driver='GeoJSON',
           encoding='utf-8')  # Specify encoding

