# -*- coding: utf-8 -*-
"""entrega1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xkgdAaQcHxTM65oTfW9E5j6L-Oh3Urz

Importar datos
"""

#Importar librerías
import geopandas as gpd
import pandas as pd

#Cargar GeoDataFrame del mapa mundial
linkGit = 'https://github.com/tareas1234512/tareas/raw/main/'
linkWorldMaps = 'worldMaps.gpkg'
countries = gpd.read_file(linkGit + linkWorldMaps, layer='countries')

#Cargar DataFrame con los datos tabulares
someDataLink = 'some_dataworld.csv'
someData = pd.read_csv(linkGit + someDataLink)

#Inspeccionar la estructura inicial
someData.info()

"""Estandarización de nombres"""

#Uniformizar la columna a Country
countries.rename(columns={'COUNTRY': 'Country'}, inplace=True)

#Convertir ambas columnas a mayúsculas
countries['Country'] = countries.Country.str.upper()

onlyDF=set(someData.Country)- set(countries.Country)
onlyGDF=set(countries.Country)- set(someData.Country)
#para verificar que países no coinciden

#instalar la librería thefuzz para emparejamiento de texto
!pip install thefuzz
from thefuzz.process import extractOne as best

#correcciones para países con denominación ambigua
manualChanges = {
    'SWAZILAND': 'ESWATINI',
    'LAOS': "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
    'SOUTH KOREA': 'KOREA (THE REPUBLIC OF)',
}
countries.replace(to_replace={'Country': manualChanges}, inplace=True)

#Recalcular diferencias
onlyDF = set(someData.Country) - set(countries.Country)
onlyGDF = set(countries.Country) - set(someData.Country)

# Emparejamiento por coincidencia aproximada
changesToDF = {country: best(country, onlyGDF)[0] for country in onlyDF}
someData.replace(to_replace={'Country': changesToDF}, inplace=True)

#Ejecutar la unión espacial
theMapAndData = countries.merge(someData, on='Country')
theMapAndData.info()

theMapAndData.info()

theMapAndData

theMapAndData.to_file("worldindicators.json")

theMapAndData.region.value_counts()

"""Mapa de América"""

#definir las regiones
regiones_america = [
    'NORTH AMERICA',
    'SOUTH AMERICA',
    'CENTRAL AMERICA AND THE CARIBBEAN'
]

#filtrar el mapa usando esa lista
america = theMapAndData[theMapAndData.region.isin(regiones_america)]

# dibujar el mapa
america.plot()

"""Asignación de mobiles"""

justDots=america.copy()
dot_value = 1000000
justDots['num_dots'] = (justDots['mobiles'] / dot_value).astype(int)

justDots

justDots = justDots.sample_points(size=justDots['num_dots']).explode(index_parts=True)

justDots

type(justDots)

justDots.reset_index(drop=True, inplace=True)
america_dots=gpd.GeoDataFrame(geometry=justDots)
america_dots

america_dots.info()

"""Dot density map"""

base=america.plot(facecolor="white",
               edgecolor='grey')
america_dots.plot(markersize=0.05, color='red',ax=base)

base=america.to_crs(8857).plot(facecolor="white",
                              edgecolor='grey')
america_dots.to_crs(8857).plot(markersize=0.05, color='red',ax=base)

america_8857=america.to_crs(8857)
america_dots_8857=america_dots.to_crs(8857)

"""#Proportional Symbol Map"""

america_8857_centroids = america_8857.copy()
america_8857_centroids['geometry'] = america_8857_centroids['geometry'].centroid

america_8857_centroids['size'] = america_8857_centroids['mobiles'].apply(lambda x: x**0.5/100)

base=america_8857.plot(facecolor="white",
                      edgecolor='grey')
america_8857_centroids.plot(
    ax=base,
    markersize=america_8857_centroids['size'],
    color='grey'
)

"""Mapa coropleto"""

america_8857.plot(america_8857.mobiles)

america_8857.plot(america_8857.population/america_8857.sq_km)

"""Discretización"""

! pip show numba mapclassify numpy

america_8857['mobiles']=america_8857.mobiles/america_8857.sq_km

import mapclassify
import numpy as np

america_8857['mobiles_density'] = america_8857['mobiles'] / america_8857['sq_km']

np.random.seed(12345)

K = 5
theVar = america_8857['mobiles_density']

ei5 = mapclassify.EqualInterval(theVar, k=K)
msd = mapclassify.StdMean(theVar)
q5 = mapclassify.Quantiles(theVar, k=K)

mb5 = mapclassify.MaximumBreaks(theVar, k=K)
ht = mapclassify.HeadTailBreaks(theVar)
fj5 = mapclassify.FisherJenks(theVar, k=K)
jc5 = mapclassify.JenksCaspall(theVar, k=K)
mp5 = mapclassify.MaxP(theVar, k=K)

class5 = ei5,msd, q5,mb5,  ht, fj5, jc5, mp5
fits = np.array([ c.adcm for c in class5])
adcms = pd.DataFrame(fits)
adcms['classifier'] = [c.name for c in class5]
adcms.columns = ['ADCM', 'Classifier']

adcms.sort_values('ADCM').plot.barh(x='Classifier')

america_8857['mobiles_density_FJ5'] = fj5.yb

america_8857[['mobiles_density','mobiles_density_FJ5']].head(20)

newLabelsForLevels={0:"0_VeryLow", 1:"1_Low", 2:"2_Middle", 3:"3_High", 4:"4_VeryHigh"}
america_8857['mobiles_density_FJ5_cat']=america_8857.loc[:,'mobiles_density_FJ5'].replace(newLabelsForLevels)
america_8857[['mobiles_density','mobiles_density_FJ5','mobiles_density_FJ5_cat']].head(20)

import matplotlib.pyplot as plt

f, ax = plt.subplots(1, figsize=(10, 10))
america_8857.plot(column='mobiles_density_FJ5_cat',
                 cmap='viridis_r',
                 categorical=True,
                 edgecolor='grey',
                 linewidth=0.3,
                 legend=True,
                 ax=ax
       )

ax.set_axis_off()

geodataframe_list = [var for var in globals() if isinstance(globals()[var], gpd.GeoDataFrame)]

print("List of GeoDataFrames in memory:")
for name in geodataframe_list:
    print(name)